#This section contains the properties that will be over-written for the Prod environment
swagger:
  host: 'iot-data-service.azurewebsites.net'
  protocols: https
server:
  port: 80
  servlet.context-path: /
management:
  endpoints:
    web.exposure.include: health,info
    jmx.exposure.exclude: '*'
  endpoint:
    shutdown.enabled: false
logging:
  level.root: info
  level.io.exnihilio: debug